### PR TITLE
Fixed groovy plugin apply order

### PR DESCRIPTION
**Pull request by rainboyan**
Fixed error:
Script '/common-plugin.gradle' line: 3

* What went wrong:
A problem occurred evaluating script.
> Failed to apply plugin 'org.gradle.groovy'.
   > Cannot add task 'groovydoc' as a task with that name already exists.

### CODE REVIEW

**Comment by rainboyan** [comment]
@puneetbehl have time to check this? I need this to build grails-async.

**Comment by puneetbehl** [comment]
Thank you for your time. I think for Gradle 6 or later, overriding a task is not allowed. Could you please describe how changing the order affect the above issue?

**Comment by rainboyan** [comment]
I use gradle 6.9 to build grails/grails-async, may be org.grails.grails-plugin overriding groovydoc task, but when changing the order, build success.
Please check it if you have time. Thank you for your time, 
I want release a new version with next grails release train, Any help if I can.

https://github.com/rainboyan/grails-async/tree/5.0.x

**Comment by rainboyan** [comment]
@puneetbehl yes, **GrailsGradlePlugin** extends Groovy. So it should be applied after groovy plugin.

**Pull request merged**
